apiVersion: v1
kind: Service

metadata:
  name: php-service

spec:
  selector:
    app: php
    env: testing
    dc: IN
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30301
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
  labels:
    app: php
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: php
  labels:
    app: php

spec:
  replicas: 1
  strategy:
          type: RollingUpdate
  selector:
    matchLabels:
      app: php
      env: testing
      dc: IN
  template:
    metadata:
      name: php
      labels:
         app: php
         env: testing
         dc: IN
    spec:
      containers:
      - name: php-con
        image: vimal13/apache-webserver-php
        volumeMounts:
          - name: php-vol
            mountPath: /var/www/html
      volumes:
      - name: php-vol
        persistentVolumeClaim:
          claimName: php-pvc
